
# Log level (one of: debug,info,warn,error,fatal,panic)
log_level: info

# HTTP API
api:
  addr: "0.0.0.0"
  port: 9321

# ETCD cluster
## Used in the API
## It can be safely ignored for client or agent configuration.
etcd:
  # List of peers on which an etcd cluster can be reached
  endpoints:
    - http://127.0.0.1:2379

