# RSSH Configuration

## Log level (one of: debug,info,warn,error,fatal,panic)
log_level: "info"

## HTTP API
api:
  addr: "0.0.0.0"
  port: 9321
  domain: "baguette.localhost"


## Gatekeeper is the public SSH frontend contacted by
## your clients to access the agent reverse forwarding
gatekeeper:
  ### Public gatekeeper SSH proxy port
  ssh_port: 2223
  ### Port range used by gatekeeper to allocate agents
  ### remote forwarding sessions.
  ssh_port_range: "31240-65535"

## ETCD cluster
## Used in the API and the gatekeeper
## It can be safely ignored for client or agent configuration.
etcd:
  ### List of peers on which an etcd cluster can be reached
  endpoints:
    - "http://127.0.0.1:2379"


## Agent configuration
agent:
  hosts:
    ## Each line in the hosts array describe a socket forwarded by the agent
    ## The forward destination MUST be an SSH server.
    -
      domain: test.baguette.localhost
      host: 127.0.0.1
      port: 22


  ## Credentials define the public / private key pair obtained by the agent
  ## upon first connection on a domain. It will reserve this domain and only
  ## allow further authentication to the domain with these credentials.
  ## e.g:
  ## -
  ##   domain: test.baguette.localhost
  ##   public_key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFEd2FsRDZvMFlrUm4rUEE5OUF4N3JIUzlsMWNrOUYyNk5FUHQ1Y3puSVZqSThWc2JQWHJUR2NGcE5wTDFESGtaeW0rM21sRmEzOW80bVQ2R1lsazZVM1FSOGpvOTU4aWwzTlZwK3c1Z3hzaWI2NFdDRENhVXFkRlI3R21sNGIxQXlXN3lTZ3pyN2dMNnIrOEorWU5PVVpTRGpPUnV4LzJKWVNwU1ZTc29KSEZTcGpsdTJLaVJiOHlwYkdNZUhlUkF3czI4azhYVHprRFkrMjM5RVBMR3BPOURUNWJ4Zk42RzNHRWV6Mk11ZkNoOThoT3ZnaC9zZnlKTXlhSTFWZU5tQXRicFNKVDM2RVRoczlnOGs5eFEvanJNVzY0UFNKWEpyMURIUkFWa3U2Qjk3NklxODNaYWFISE1yMk5PRnk2ZC9Zb3NQUUhVdlZkVGRtMFJqREx2ZmQK
  ##   private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpiYXI6IHJhYgpmb286IG9vZgoKTUlJRXBBSUJBQUtDQVFFQThHcFErcU5HSkVaL2p3UGZRTWU2eDB2WmRYSlBSZHVqUkQ3ZVhNNXlGWXlQRmJHegoxNjB4bkJhVGFTOVF4NUdjcHZ0NXBSV3QvYU9KaytobUpaT2xOMEVmSTZQZWZJcGR6VmFmc09ZTWJJbSt1RmdnCndtbEtuUlVleHBwZUc5UU1sdThrb002KzRDK3EvdkNmbURUbEdVZzR6a2JzZjlpV0VxVWxVcktDUnhVcVk1YnQKaW9rVy9NcVd4akhoM2tRTUxOdkpQRjA4NUEyUHR0L1JEeXhxVHZRMCtXOFh6ZWh0eGhIczlqTG53b2ZmSVRyNApJZjdIOGlUTW1pTlZYalpnTFc2VWlVOStoRTRiUFlQSlBjVVA0NnpGdXVEMGlWeWE5UXgwUUZaTHVnZmUraUt2Ck4yV21oeHpLOWpUaGN1bmYyS0xEMEIxTDFYVTNadEVZd3k3MzNRSURBUUFCQW9JQkFRRFR4TktQOUVKVXNjU3EKdFQ1eVVYeTFFSnI4V1RSNjFIMThIK1MrMnhxaTRLMG83dDc3bkJPVzZrdnUyejdNaS9ieEg1S0hXQkZxMmlMVgpwbUJUdVRwTzhZMzhWdHdqMTczSW9nVUlUWnVqLzdGL3NDRXJIcFFheWYvUjhTZjBXMVM3bnVza3V2aG5nWldkCisxYVpPLzZSeG94REp6WXJaeHpLVDY0UXFpMFhibGhYY0M0cTNIMkpic3NSU1hmaGFrV2pDQytRRTA5VHJrMisKaGo3NTBuS0tibGR3aVdIRnZZNmJPSVFGUjZvUUhXRzZVSlNOaHV3N3lwdFdVYVViZFVPREtLNGVGdU5VcHFWTwpaM2dHL3U5ZUxQeU5vWXl1dnQ1ZjVJbGxaZVhvcHhiZjU3WStqaVpFUFVraXB0bXhhRmMyMEs1cFc4YU5ON0t3ClJwWlk0U0FCQW9HQkFQbTlTM1I1TlN3VWhiWkROdjV6eC82MGI3NDF1eTEvcXR5WUlNdU5YWno0L1ZaYmIrTHUKc0w2MnlLQU14Vkh0N2s3TXFDa1lMV2MxY2o3MS9UOUVyUHlDWDVpNTRzdWkzUklmR2ZXUytuNUxkVlREZ1BWUwp4QmlPbmIrb2dtYWF6VktCT2xzaDk1bkN6Qmx4Nit4cDhBb3ptb2Z6MHdxK2c4N0tBQjgxOFNxUkFvR0JBUFp4Ckx4RVNhbkdNOTk5Z1E0RUd0dW1tbjFTMXU3OTNzZ1R4aC9rRTJqM2h2UnJ1dlA4cUFXS2FtM2ZIQ09lL1IrTmgKK1RNWFViQjZDcmQvNTZybTVxQndIUFN2Vk5valBmblhaejUxZVhEVHNSUXUzbllQR0NyWlhUV3ZMSzIydWtSYQpRd3oxNkRYV212NUo0KytJOTRhYk5LQ2tETHp2TjRMVWVUODYrU2FOQW9HQkFMVTBaRXRlcHZZVTdmQVJWUlhMCmJKR2kybkZwQ3ljNE93RlVZSGRSVzF0S1RvY2FVVlNYWENjRStRMG9Od1A3WDY1TlVMYUFsSEVPbHBhWVplaEMKTEVJTFZ0RzZEcFV5MXJVUFhBYVRYcTNFa3AydVBTUERxZ1VuZGM1YXRrTThqejRPQmdtWjI4MzFTYUlzeHNJRApHK2hMQ1JVY0ZVVDJkeXpUNU1MQW9Qd0JBb0dBUS8yc0Q1aTJGMGZlSnhtbTVoVVZKOWRaaEFSem5QcUgrY2N0ClRXMmlUSXBZSXZNVTM0MFdQcjhLLzN2QklEYnN2WFlOUzZRMlhHci9RK3NjM2xDLzlpbVlRNFdQOG5MZ3FXcGQKU0tVZWNSdG1jbndQMGlDTitWeG8wK1BWZnNPNEZoMlUvQ0ZvQkZxRi9ud2lUN2JKRzdEOFR3bVRuaGlkaHhIWgp0YkV1aGcwQ2dZQTdIVitjQW1VSDB2Wk5lZjh2dmJ1Uk8yK3dwUnN0WlMxcmc4Tm1KbUVoaGhEMURaWWszS1ZuCjNpMERHQkZrRjJWVmZ1L2RuUzBkbktEeXdUaXdCS3I5YytoWmI0VEkvWlQ5NEJzYUZONkxSU2ZGQzJmY05Yc3AKbkRKbkgvT1E2b0taNjVZdEVoMmFkaXgwMEFrUzNSem8rSGE5dnJHMWZUL2xVZlRBNWdBZHpBPT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  credentials: []
