version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: 'http://127.0.0.1:2379'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://127.0.0.1:2379'
    network_mode: host
    restart: on-failure
  rssh_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: xide/rssh
    environment:
      RSSH_CONFIG: /.rssh.yml
      RSSH_LOG_LEVEL: 'debug'
      RSSH_API_ADDR: '0.0.0.0'
      RSSH_API_PORT: '9321'
      RSSH_API_ETCD_ENDPOINTS: 'http://127.0.0.1:2379'
    command: api
    volumes:
      - .rssh.yml:/.rssh.yml
    depends_on:
      - etcd
    network_mode: host
  rssh_gatekeeper:
    build:
      context: .
      dockerfile: Dockerfile
    image: xide/rssh
    environment:
      RSSH_CONFIG: /.rssh.yml
      RSSH_LOG_LEVEL: 'debug'
      RSSH_GATEKEEPER_ADDR: '0.0.0.0'
      RSSH_GATEKEEPER_PORT: '2223'
      RSSH_GATEKEEPER_PORT_RANGE: '31240-65535'
      RSSH_GATEKEEPER_ETCD_ENDPOINTS: 'http://127.0.0.1:2379'
    command: gatekeeper
    volumes:
      - .rssh.yml:/.rssh.yml
    depends_on:
      - etcd
    network_mode: host