version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://0.0.0.0:2379'
    restart: on-failure
  rssh_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: xide/rssh
    environment:
      RSSH_ETCD: 'http://etcd:2379'
      RSSH_ADDR: '0.0.0.0'
      RSSH_PORT: '2222'
    command: server
    depends_on:
      - etcd
    ports:
      - 2222:2222
