version: 2
workflows:
  version: 2
  publish:
    jobs:
      - build_images

jobs:
  build_images:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker image
          command: docker build -t sigbilly/rssh:$CIRCLE_BRANCH
      - run:
          name: Push Docker image
          command: docker push sigbilly/rssh:$CIRCLE_BRANCH
