version: 2
workflows:
  version: 2
  publish:
    jobs:
      - build_images
      - standalone_executables

jobs:
  build_images:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker image
          command: docker build -t sigbilly/rssh:$CIRCLE_BRANCH .
      - run:
          name: Push Docker image
          command: docker push sigbilly/rssh:$CIRCLE_BRANCH

  standalone_executables:
    docker:
      - image: golang:1.12-stretch
    steps:
      - checkout
      - run: go get -u github.com/tcnksm/ghr
      - run: go mod download
      - run: |
          GOARCHS=(386 amd64 arm arm64)
          GOOSES=(darwin linux windows)
          
          mkdir release
          
          for GOARCH in ${GOARCHS[@]}
          do
            for GOOS in ${GOOSES[@]}
            do
              echo "Building for $GOOS-$GOARCH"
              CGO_ENABLED=0 go build -o release/rssh-${GOOS}-${GOARCH}
            done
          done
      - run: ghr latest release